== Description
Ensemble de fonctions réutilisables pour les projets rust/sqlx

La base de donnée principale doit être Postgres. Son url doit être définie dans un .env ou les variables d'environnement avec le code DATABASE_URL.
Pour Teliway, les codes doivent être les suivants:

- DATABASE_GTRA_URL
- DATABASE_GTLS_URL
- DATABASE_GTRI_URL
- DATABASE_EXPRESS_URL

== Usage
[,rust]
----
let databases = databases::Databases::init(env::vars()).await?;
let pgpool = databases.default;
let gtrapool = databases.get_by_code("gtra");
----

== Versions
0.18.0 16/01/25::
Ajout de LIMIT dans set_pagination

0.17.0 20/12/24::
refactorisation one_to_many. Ajout
0.16.0 17/12/24::
Ajout with_xxx sur Pagination

0.15.0 17/12/24::
Pagination::new()

0.13.2 06/12/24::
ajout build_pagination

0.13.1 06/12/24::
ajout PaginatedRequest

0.13.0 06/12/24::
Ajout set_pagination

0.12.0 06/12/24::
supprimée pour cause erreur
Ajout set_pagination

0.10.0 03/12/24::
Ajout parsers et formatters de date

0.9 02/12/24::
Evol: Si pas de base de données postgres local, mais teliway uniquement

0.5.0 05/08/24::
upgrade sqlx 0.8
remplacement feature sqlx time par chrono

0.4.4 01/07/24::
extract: 1ToMany depuis une liste non triée
extract_from_ordered: 1ToMany depuis une liste triée

0.4.3 17/06/24::
Test sur one_to_many::as_vec
Augmentation capacité à 500

0.4.2 11/06/24::
Ajout and_in

0.4.1 12/04/24::
Ajout and_starts_like

0.4.0 14/03/2024::
Ajout OneToMany

0.3.2 21/12/2023::
renommage propriété builder -> internal
ajout espace avant push

0.3.1 21/12/2023::
new et push sur Builder

0.3.0 21/12/2023::
Ajout Pg/MySqlBuilder

0.2.0 12/10/2023::
Dans init, indication du nb max connexions

0.1.0 13/09/2023::
Struct Database pour gérer une base Postgres (default) et les bases téliways définies dans les variables d'environnement.
